* personal settings

#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-

(setq my-notes-directory "~/Dropbox/org/reading-notes"
      my-bibliography "~/Dropbox/texmf/bibtex/bib/misc/rvf.bib"
      my-library-path "~/Documents/References/")
#+end_src

* emacs general settings

#+begin_src emacs-lisp
(use-package emacs
  :config
  (ido-mode 1)
  :custom
  (confirm-nonexistent-file-or-buffer nil)
  (custom-file (concat user-emacs-directory "custom.el"))
  (frame-title-format "%b: %+%+ %f")
  (mouse-drag-copy-region t)
  :init
  (global-visual-line-mode))
#+end_src

* use-package

#+begin_src emacs-lisp
(straight-use-package 'use-package)
#+end_src

* Packages

** auctex                                                              :math:

https://www.gnu.org/software/auctex/

#+begin_quote
AUCTeX is an extensible package for writing and formatting TeX files in GNU Emacs and XEmacs. It supports many different TeX macro packages, including AMS-TeX, LaTeX, Texinfo, ConTeXt, and docTeX (dtx files).
#+end_quote

#+begin_src emacs-lisp
(use-package tex
  :straight auctex
  :mode ("\\.tikz\\'" . latex-mode)
  :init
  (defun my-latex-config ()
    (TeX-add-symbols '("deg"))
    (TeX-add-symbols '("emph" 1))
    (TeX-add-symbols '("ne"))
    (TeX-add-symbols '("to"))
    (LaTeX-add-environments '("definition" LaTeX-env-label)
			    '("theorem" LaTeX-env-label)
			    '("lemma" LaTeX-env-label)
			    '("corollary" LaTeX-env-label)
			    '("proposition" LaTeX-env-label)
			    '("problem" LaTeX-env-label)
			    '("remark" LaTeX-env-label)
			    '("example" LaTeX-env-label))
    (add-to-list 'LaTeX-label-alist '("definition" . "def:"))
    (add-to-list 'LaTeX-label-alist '("theorem" . "thm:"))
    (add-to-list 'LaTeX-label-alist '("lemma" . "lem:"))
    (add-to-list 'LaTeX-label-alist '("corollary" . "cor:"))
    (add-to-list 'LaTeX-label-alist '("proposition" . "prop:"))
    (add-to-list 'LaTeX-label-alist '("problem" . "prob:"))
    (add-to-list 'LaTeX-label-alist '("remark" . "rem:"))
    (add-to-list 'LaTeX-label-alist '("example" . "exa:"))
    (add-to-list 'reftex-label-alist '("definition" ?d "def:" "~\\ref{%s}" nil ("Definition" "definition")))
    (add-to-list 'reftex-label-alist '("theorem" ?h "thm:" "~\\ref{%s}" nil ("Theorem" "theorem")))
    (add-to-list 'reftex-label-alist '("lemma" ?l "lem:" "~\\ref{%s}" nil ("Lemma" "lemma")))
    (add-to-list 'reftex-label-alist '("corollary" ?c "cor:" "~\\ref{%s}" nil ("Corollary" "corollary")))
    (add-to-list 'reftex-label-alist '("proposition" ?p "prop:" "~\\ref{%s}" nil ("Proposition" "proposition")))
    (add-to-list 'reftex-label-alist '("problem" ?b "prob:" "~\\ref{%s}" nil ("Problem" "problem")))
    (add-to-list 'reftex-label-alist '("remark" ?r "rem:" "~\\ref{%s}" nil ("Remark" "remark")))
    (add-to-list 'reftex-label-alist '("example" ?e "rem:" "~\\ref{%s}" nil ("Example" "example")))
    (TeX-run-style-hooks "tikz")
    (TeX-run-style-hooks "tkz-graph")
    (TeX-run-style-hooks "tkz-berge"))
  :custom
  (TeX-auto-save t)
  (TeX-electric-escape t)
  (TeX-insert-braces nil)
  (TeX-parse-self t)
  (TeX-save-query nil)
  (reftex-plug-into-AUCTeX t)
  (reftex-use-external-file-finders t)
  :hook
  (LaTeX-mode . turn-on-cdlatex)
  (LaTeX-mode . my-latex-config)
  (LaTeX-mode . turn-on-reftex))
#+end_src

** cdlatex                                                             :math:

https://staff.fnwi.uva.nl/c.dominik/Tools/cdlatex/

#+BEGIN_QUOTE
CDLaTeX is a minor mode for Emacs supporting fast insertion of environment templates and math stuff in LaTeX. Similar commands are also offered as part of the AUCTeX package, but it is not the same - CDLaTeX focuses on speediness for inserting LaTeX constructs. I myself am using CDLaTeX on top of AUCTeX.
#+END_QUOTE

The settings in =cdlatex-math-symbol-alist= are useful also when writing math in org-mode.

It was needed to customize =cdlatex-takeover-parenthesis=, see [[https://github.com/cdominik/cdlatex/issues/15#issuecomment-864529972][this issue]].

#+begin_src emacs-lisp
(use-package cdlatex
  :straight t
  :custom
  (cdlatex-math-symbol-alist
   '(( ?c   ("\\colon"))
     ( ?m   ("\\mu" "\\mapsto"))
     ( ?p   ("\\pi" "\\varpi" "\\perp"))
     ( ?o   ("\\omega" "\\oplus"))
     ( ?O   ("\\Omega" "\\mathrm{Orb}"))
     ( ?S   ("\\Sigma" "\\mathrm{Stab}"))
     ( ?T   ("\\bigtriangleup"))
     ( ?-   ("\\cap" "\\leftrightarrow" "\\longleftrightarrow"))
     ( ?.   ("\\ldots" "\\cdots" "\\cdot"))
     ( ?*   ("\\times" "\\otimes"))
     ( ?<   ("\\leq" "\\langle" "\\trianglelefteq"))
     ( ?>   ("\\geq" "\\rangle" "\\trianglerighteq"))
     ( ?=   ("\\simeq"))
     ( ?\[  ("\\subseteq"))))
  (cdlatex-math-modify-alist
   '(( ?a "\\overrightarrow" nil t nil nil)
     ( ?k "\\mathfrak" nil t nil nil)
     ( ?B "\\mathbb"         nil t nil nil)))
  (cdlatex-command-alist
   '(("bin"  "Insert \\binom{}{}"
      "\\binom{?}{}"       cdlatex-position-cursor nil nil t)
     ("norm" "Insert \\Vert \\Vert"
      "\\Vert ?\\Vert"     cdlatex-position-cursor nil nil t)
     ("gen"  "Insert \\langle \\rangle"
      "\\langle ?\\rangle" cdlatex-position-cursor nil nil t)
     ("set"  "Insert a set"
      "\\{?\\mid \\}"      cdlatex-position-cursor nil nil t)))
  (cdlatex-simplify-sub-super-scripts nil)
  (cdlatex-takeover-parenthesis nil))
#+end_src

** citar

https://github.com/emacs-citar/citar

#+begin_quote
Emacs package to quickly find and act on bibliographic references, and edit org, markdown, and latex academic documents.
#+end_quote

#+begin_src emacs-lisp
    (use-package citar
      :straight t
      :custom
      (citar-bibliography my-bibliography)
      (citar-library-paths `(,my-library-path))
      (citar-notes-paths `(,my-notes-directory)))
#+end_src

** corfu

https://github.com/minad/corfu

#+begin_quote
corfu.el - COmpletion in Region FUnction
#+end_quote

#+begin_src emacs-lisp
(use-package corfu
  :straight t
  :custom
  (corfu-auto t)
  :init
  (global-corfu-mode))
#+end_src

*** cape

By default, =corfu= works only on =.el= files. For it to be able to complete, say, by the words in a dictionary or words in the buffer, it needs /extensions/ given by =cape=.

https://github.com/minad/cape

#+begin_quote
cape.el - Completion At Point Extensions
#+end_quote

#+begin_src emacs-lisp
(use-package cape
  :straight t
  :init
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-dict))
#+end_src

Note that in order to use a non-English dictionary, it is useful a local variable like =cape-dict-file: "/usr/share/dict/spanish"=.

** embark

https://github.com/oantolin/embark

#+begin_quote
Emacs Mini-Buffer Actions Rooted in Keymaps
#+end_quote

#+begin_src
(use-package embark
  :straight t
  :bind
  (("C-=" . embark-act)))
#+end_src

** jupyter

#+begin_quote
An interface to communicate with Jupyter kernels.
#+end_quote

https://github.com/nnicandro/emacs-jupyter

The recent versions do not work with my ubuntu. The issue is described [[https://github.com/nnicandro/emacs-zmq/issues/48][here]]. So far the workaround is to manually compile =emacs-zmq.so= in =straight/build= and copy it to the other folder there. Also, manually return =jupyter=  repo to commit =487a755= in the corresponding folder. This gives some warnings =Unknown type: json-plist=, but otherwise seems to work. With these libraries it seems to work (it seems that the most important version not to upgrade is =jupyter_core=).

#+begin_src shell
(pycliques-dev) rafael@dell2:~$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.17.2
ipykernel        : 6.26.0
ipywidgets       : 8.1.1
jupyter_client   : 8.6.1
jupyter_core     : 5.7.2
jupyter_server   : 1.23.4
jupyterlab       : 4.0.8
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.0.6
qtconsole        : 5.5.1
traitlets        : 5.14.3
#+end_src

#+begin_src emacs-lisp
(use-package jupyter
  :if (executable-find "jupyter")
  :straight t
  :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((latex . t)
     (python . t)
     (jupyter . t))))
#+end_src

** magit

https://magit.vc

#+begin_quote
Magit is a complete text-based user interface to Git.
#+end_quote

#+begin_src emacs-lisp
(use-package magit
  :straight t
  :bind ("C-c m" . magit-status))
#+end_src

* marginalia

https://github.com/minad/marginalia

#+begin_quote
marginalia.el - Marginalia in the minibuffer
#+end_quote

#+begin_src emacs-lisp
(use-package marginalia
  :straight t
  :init
  (marginalia-mode))
#+end_src

** mixed-pitch

https://gitlab.com/jabranham/mixed-pitch

#+begin_src quote
Mix fixed-pitch and variable-pitch fonts in Emacs
#+end_src

#+begin_src emacs-lisp
(use-package mixed-pitch
  :straight t
  :hook
  (text-mode . mixed-pitch-mode))
#+end_src

** modus themes

https://gitlab.com/protesilaos/modus-themes

#+begin_src emacs-lisp
(use-package modus-themes
  :straight t
  :if (display-graphic-p)
  :init
  ;; Add all your customizations prior to loading the themes
  (setq modus-themes-italic-constructs t
        modus-themes-bold-constructs nil
        modus-themes-region '(bg-only no-extend))
  (load-theme 'modus-operandi :no-confirm))
#+end_src

** orderless

https://github.com/oantolin/orderless

#+begin_quote
Emacs completion style that matches multiple regexps in any order
#+end_quote

#+begin_src emacs-lisp
(use-package orderless
  :straight t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

** org

- I am setting =org-src-preserve-indentation= to =t= since otherwise source blocks are changed (indented) after edited.

#+begin_src emacs-lisp
(use-package org
  :config
  (custom-theme-set-faces
   'user
   `(org-level-4 ((t (:height 1.1))))
   `(org-level-3 ((t (:height 1.2))))
   `(org-level-2 ((t (:height 1.3))))
   `(org-level-1 ((t (:height 1.5))))
   `(org-document-title ((t (:height 1.75)))))
  :custom
  (org-hide-emphasis-markers t)
  (org-src-preserve-indentation t)
  (org-support-shift-select t))
#+end_src

** org-fragtog

https://github.com/io12/org-fragtog

#+begin_quote
Automatically toggle Org mode LaTeX fragment previews as the cursor enters and exits them
#+end_quote

For some reason, by default the previews are too small, so we have to increase the scale.

#+begin_src emacs-lisp
(use-package org-fragtog
  :straight t
  :after org
  :custom
  (org-format-latex-header (concat org-format-latex-header "\n\\usepackage{lxfonts}"))
  (org-format-latex-options (plist-put org-format-latex-options :scale 2.2))
  :init
  (add-hook 'org-mode-hook 'org-fragtog-mode))
#+end_src

** org-noter

By default =C-M-.= is bound to =org-noter-sync-current-note=.

https://github.com/org-noter/org-noter

#+begin_src emacs-lisp
(use-package org-noter
  :straight
  (:repo "org-noter/org-noter"
         :host github
         :type git
         :files ("*.el" "modules/*.el"))
  :after (org nov pdf-tools)
  :bind (("<f5> n" . org-noter))
  :custom
  (org-noter-auto-save-last-location t)
  (org-noter-notes-search-path `(,my-notes-directory)))
#+end_src

** org-roam

#+begin_src emacs-lisp
(use-package org-roam
  :straight t
  :after org
  :custom
  (org-roam-directory my-notes-directory)
  :init
  (org-roam-db-autosync-mode))
#+end_src

** nov

https://depp.brause.cc/nov.el/

Useful to open =epub= files and for org-noter to annotate files in =epub= format. In fact, =doc-view=, which is already included, can open files in =djvu= and =epub=. But, it converts every page of an =epub= file to an image, while =nov= can be used to access the text. We have to tell Emacs to open =epubs= in this mode, otherwise it will use =doc-view=.

#+begin_src emacs-lisp
(use-package nov
  :straight t
  :mode ("\\.epub\\'" . nov-mode))
#+end_src

** pdf-tools

https://github.com/vedang/pdf-tools

#+begin_quote
PDF Tools is, among other things, a replacement of DocView for PDF files. The key difference is that pages are not pre-rendered by e.g. ghostscript and stored in the file-system, but rather created on-demand and stored in memory.
#+end_quote

#+begin_src emacs-lisp
(use-package pdf-tools
  :if window-system
  :straight t
  :config
  (pdf-tools-install))
#+end_src

* vertico

https://github.com/minad/vertico

#+begin_quote
vertico.el - VERTical Interactive COmpletion
#+end_quote

#+begin_src emacs-lisp
(use-package vertico
  :straight t
  :init
  (vertico-mode))
#+end_src


